packages:
  - apps/*
  - packages/*

allowBuilds:
  '@bufbuild/buf': true
  esbuild: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    antd: '6'
    nodemailer: '9'
