packages:
  - apps/*
  - packages/*

allowBuilds:
  '@bufbuild/buf': set this to true or false
  esbuild: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    antd: '6'
