packages:
  - apps/*
  - packages/*

overrides:
  "@auth/core@0.41.3>nodemailer": 9.0.3
  "next-auth@5.0.0-beta.32>nodemailer": 9.0.3
  brace-expansion@<1.1.16: 1.1.16
  "brace-expansion@>=5.0.0 <5.0.8": 5.0.8
  postcss: 8.5.23
  path-to-regexp: 8.4.2
  sharp: 0.35.3

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
